version: '3'
services:
  proxy:
    image: "iiif-proxy-httpd:latest"
    build: .
    container_name: httpd_proxy
    ports:
      - "8000:80"
    volumes:
      - ../common:/usr/local/apache2/htdocs

